CREATE TABLE todos (
id SERIAL PRIMARY KEY,
title VARCHAR (255) NOT NULL,
description VARCHAR (255) NOT NULL,
status VARCHAR (255),
created_on DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(255),
  passwordDigest VARCHAR(255)
);
